
version: "3"

services:
    app:
        build:
            context: .
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            # http://localhost:8080/
            - "8080:80"
        depends_on:
            - php
    php:
        # https://hub.docker.com/_/php
        image: php:fpm
        volumes:
            - ./app:/var/www/html
