
version: "3"

services:
    app:
        image: amazonlinux:latest
        # build:
        #     context: .
        volumes:
            - ./app:/app
            # - /sys/fs/cgroup:/sys/fs/cgroup:ro
        tty: true
        ports:
            - "8080:80"
        # privileged: true
        # cap_add:
        #     - SYS_ADMIN
        # security_opt:
        #     - seccomp:unconfined
