
version: "3"

services:
    app:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        depends_on:
            - php
        ports:
            - 8080:80
        # image: nginx:1
        volumes:
            - ./app:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/html

    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        # image: php:fpm
        volumes:
            - ./app:/var/www/html
        working_dir: /var/www/html
