
version: "3"

services:
    app:
        depends_on:
            - go
        image: nginx:1
        # networks:
        #     - docker-sample-golang-gin2-network
        volumes:
            - ./app:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        tty: true
        working_dir: /var/www/html

    go:
        build:
            context: .
            dockerfile: ./go/Dockerfile
        # networks:
        #     - docker-sample-golang-gin2-network
        # 左のポートは app で使用している 8080 以外であればなんでも良い。
        # 右側の内部で扱うポートが大事。← 関係ない。main.go の r.Run(":8080") が大事だった。
        # コンテナ内で扱う8080ポートは go:8080 でアクセスできる。← 関係ない。main.go の r.Run(":8080") が大事だった。
        # depends_on しておけば？ networks で繋ぐ必要はない
        # ports:
            # - 18080:8080
            # - 18080:80
        volumes:
            - ./app:/var/www/html
        working_dir: /var/www/html

# networks:
#     docker-sample-golang-gin2-network:
#         name: docker_sample_golang_gin2_network
