
version: "3"

services:
    app:
        build:
            context: .
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - docker-sample-network
        environment:
            - VIRTUAL_HOST=docker.sample
    php:
        # https://hub.docker.com/_/php
        image: php:fpm
        volumes:
            - ./app:/var/www/html
        networks:
            - docker-sample-network

networks:
    docker-sample-network:
        name: docker_sample_network
