# web:
#   image: nginx
#   volumes:
#    - ./templates:/etc/nginx/templates
#   ports:
#    - "8080:80"
#   environment:
#    - NGINX_HOST=foobar.com
#    - NGINX_PORT=80

services:
    nginx:
        build:
            context: .
        volumes:
         - .:/var/www/html
        ports:
         - "8080:80"
        # networks:
        #     default:
        #         aliases:
        #             - local2.sample
