
version: "3"

services:
    app:
        image: nginx:1
        volumes:
            - ./app:/var/www/html
            - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:80
        tty: true
        working_dir: /var/www/html
