# https://hub.docker.com/_/wordpress

version: "3"

services:
    mysql:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            TZ: 'Asia/Tokyo'
        volumes:
            - ./../mysql:/var/lib/mysql

    wordpress:
        image: wordpress:latest
        # image: wordpress:php8.0-fpm-alpine
        restart: always
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ./wordpress:/var/www/html

# volumes:
#     wordpress:
#     db:
