
version: "3"

services:
    app:
        build:
            context: .
        volumes:
            - ./app:/var/www/html
        # コンテナを起動し続けるための項目
        tty: true
        working_dir: /var/www/html
